# Generated by Django 3.2.4 on 2021-07-07 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_height',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_width',
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='catalog/'),
        ),
    ]
